blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/millsydotdev/forge/tree/main/docs
    about: Check the documentation before opening an issue
  - name: Discord Community
    url: https://discord.gg/TVmaw9354z
    about: Ask questions and get help in our Discord
